/** Quiet Patisserie Editorial: a maker story that reads like an independent food-journal profile. */
import { ArrowUpRight, Heart } from "lucide-react";
import { Link } from "wouter";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

export default function About() {
  return <div className="min-h-screen bg-[#fbf9f4] text-[#342b29]"><SiteHeader /><main>
    <section className="container py-6 sm:py-10"><div className="grid overflow-hidden bg-[#efeeeb] lg:grid-cols-[.9fr_1.1fr]"><div className="min-h-[430px] lg:order-2"><img className="h-full w-full object-cover object-center" src="/images/photo-1556910103-1c02745aae4d.jpg" alt="Baker at work in a kitchen" /></div><div className="flex flex-col justify-between px-8 py-12 sm:px-14 lg:order-1 lg:py-16"><div><p className="eyebrow">A note from the studio</p><h1 className="display-title mt-5 text-[62px] sm:text-[78px]">Meet<br /><em className="font-normal">Maya.</em></h1><p className="mt-6 max-w-md text-sm leading-6 text-[#655653]">I’m the hands behind Petal &amp; Crumb: baker, flower gatherer, determined advocate for the second slice.</p></div><p className="mt-10 font-display text-[25px] leading-[1.04] text-[#4b3b38]">“The sweetest details are the ones people remember.”</p></div></div></section>
    <section className="container grid gap-12 py-16 sm:py-24 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">The way I work</p><h2 className="display-title mt-5 text-[52px] sm:text-[62px]">Good ingredients, good questions, a little surprise.</h2></div><div className="space-y-7 text-[15px] leading-7 text-[#5c4e49]"><p>Petal &amp; Crumb grew from a tiny home kitchen and a love of making ordinary occasions feel a little ceremonial. The work is personal by design: I want to know the flavor that reminds you of home, the colors you’re wearing, and the people you can’t wait to feed.</p><p>My cakes are softly styled, naturally seasonal, and made from scratch in small batches. They’re meant to be eaten, admired, and remembered long after the candles come down.</p><div className="flex flex-wrap gap-3 pt-2"><span className="inline-flex items-center gap-2 border border-[#dfd0c9] bg-[#fffdfa] px-4 py-3 text-xs font-medium"><Heart size={15} className="text-[#a8515a]"/> Baked from scratch</span><span className="inline-flex items-center gap-2 border border-[#dfd0c9] bg-[#fffdfa] px-4 py-3 text-xs font-medium"><Heart size={15} className="text-[#a8515a]"/> Seasonal flowers</span></div></div></section>
    <section className="bg-[#342b29] px-5 py-16 text-[#f8f3ed] sm:px-8"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow text-[#d9aca9]">For gatherings of any size</p><h2 className="mt-5 font-display text-[52px] leading-[.92] tracking-[-.055em] sm:text-[68px]">Tell me what you’re celebrating.</h2><Link href="/custom-order" className="button-rose mt-8 px-6 py-4">Build a custom quote <ArrowUpRight size={14} /></Link></div></section>
  </main><SiteFooter /></div>;
}
