/** Quiet Patisserie Editorial: straightforward contact details and useful policy answers, with no fabricated social proof. */
import { useState } from "react";
import { Mail, MapPin, Send } from "lucide-react";
import { toast } from "sonner";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { faqItems } from "@/lib/bakeryData";

export default function Contact() {
  const [open, setOpen] = useState<number | null>(0);
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); toast.success("Your note is ready for the studio.", { description: "This demo form does not send an email yet." }); event.currentTarget.reset(); };
  return <div className="min-h-screen bg-[#fbf9f4] text-[#342b29]"><SiteHeader /><main>
    <section className="container py-14 sm:py-20"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Questions, dates, sweet ideas</p><h1 className="display-title mt-5 text-[66px] sm:text-[88px]">Let’s say<br /><em className="font-normal">hello.</em></h1><p className="mt-6 max-w-sm text-sm leading-6 text-[#645550]">For a celebration that needs some extra thought, tell us a little about it. For custom cake pricing, the order studio is the quickest first step.</p><div className="mt-8 space-y-4 text-sm"><a href="mailto:hello@petalandcrumb.com" className="flex items-center gap-3 text-[#523f3b]"><Mail size={17} className="text-[#a8515a]"/> hello@petalandcrumb.com</a><p className="flex items-center gap-3 text-[#523f3b]"><MapPin size={17} className="text-[#a8515a]"/> Portland, Oregon · pickup + local delivery</p></div></div><form onSubmit={handleSubmit} className="border border-[#ddcec7] bg-[#fffdf9] p-6 shadow-[0_20px_50px_rgba(83,59,50,.06)] sm:p-9"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a8515a]">Studio inquiry</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold">Your name<input required className="field-base mt-2" placeholder="Your name" /></label><label className="text-xs font-semibold">Email<input required type="email" className="field-base mt-2" placeholder="you@example.com" /></label><label className="text-xs font-semibold sm:col-span-2">What are you celebrating?<input className="field-base mt-2" placeholder="A birthday, a shower, a Tuesday..." /></label><label className="text-xs font-semibold sm:col-span-2">A little more detail<textarea required className="field-base mt-2 min-h-32 resize-y" placeholder="Tell us about your idea." /></label></div><button className="button-rose mt-6 px-5 py-4" type="submit">Send a note <Send size={14} /></button><p className="mt-4 text-xs leading-5 text-[#7a6660]">For the fastest price and availability check, please use the custom order studio.</p></form></div></section>
    <section className="bg-[#f4e4e4] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Before you order</p><h2 className="display-title mt-5 text-[53px] sm:text-[64px]">Helpful<br /><em className="font-normal">answers.</em></h2><p className="mt-5 max-w-xs text-sm leading-6 text-[#685450]">A few practical notes before we make something lovely together.</p></div><div className="border-t border-[#d8c2c0]">{faqItems.map((item, index) => <div key={item.question} className="border-b border-[#d8c2c0]"><button type="button" onClick={() => setOpen(open === index ? null : index)} className="flex w-full items-center justify-between gap-5 py-5 text-left font-display text-2xl"><span>{item.question}</span><span className="font-sans text-lg text-[#a8515a]">{open === index ? "−" : "+"}</span></button>{open === index && <p className="-mt-1 max-w-2xl pb-5 text-sm leading-6 text-[#675550]">{item.answer}</p>}</div>)}</div></div></section>
    <section className="container py-10"><p className="mx-auto max-w-3xl text-center text-xs leading-5 text-[#7b6660]">Petal &amp; Crumb is a home-based cottage food business. Products are made in a kitchen that also handles wheat, dairy, eggs, soy, and tree nuts. Please share all dietary needs before reserving your date.</p></section>
  </main><SiteFooter /></div>;
}
