/** Quiet Patisserie Editorial: a calm seasonal menu with real-feeling prices and generous visual rhythm. */
import { ArrowUpRight, Check } from "lucide-react";
import { Link } from "wouter";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { menuItems } from "@/lib/bakeryData";

export default function Menu() {
  return <div className="min-h-screen bg-[#fbf9f4] text-[#342b29]"><SiteHeader /><main>
    <section className="container py-14 sm:py-20"><p className="eyebrow">A small, seasonal menu</p><div className="mt-4 grid gap-8 lg:grid-cols-[1fr_.75fr]"><h1 className="display-title text-[66px] sm:text-[90px]">Sweet things,<br /><em className="font-normal">made slowly.</em></h1><p className="self-end max-w-md text-sm leading-6 text-[#62534e]">A few generous favorites, each baked to order and decorated by hand. Custom cake pricing begins in the order studio.</p></div></section>
    <section className="container pb-16 sm:pb-24"><div className="grid gap-x-4 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{menuItems.map((item) => <article key={item.title} className="group"><div className="visual-tile aspect-[.9]"><img src={item.image} alt={item.title} /></div><div className="mt-4 flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#a8515a]">{item.tag}</p><h2 className="mt-2 font-display text-[30px] leading-none">{item.title}</h2></div><p className="pt-1 text-xs font-semibold text-[#825a56]">{item.price}</p></div><p className="mt-3 text-sm leading-6 text-[#6b5c57]">{item.detail}</p></article>)}</div></section>
    <section className="bg-[#342b29] px-5 py-16 text-[#f7f2eb] sm:px-8 sm:py-20"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[.82fr_1.18fr]"><div><p className="eyebrow text-[#d9aca9]">Planning something larger?</p><h2 className="mt-5 font-display text-[52px] leading-[.92] tracking-[-.055em]">Start with the shape of the gathering.</h2></div><div className="grid gap-3 sm:grid-cols-2"><div className="border border-white/15 p-5"><Check size={18} className="text-[#d9aca9]"/><p className="mt-4 text-sm font-semibold">Built around your guest count</p><p className="mt-2 text-sm leading-6 text-[#d8ccc4]">Pick a size and see a transparent starting price.</p></div><div className="border border-white/15 p-5"><Check size={18} className="text-[#d9aca9]"/><p className="mt-4 text-sm font-semibold">Designed for your date</p><p className="mt-2 text-sm leading-6 text-[#d8ccc4]">Only real available dates appear in the calendar.</p></div></div></div><div className="mx-auto mt-9 max-w-[1180px]"><Link href="/custom-order" className="button-rose px-5 py-4">Build a custom quote <ArrowUpRight size={14} /></Link></div></section>
  </main><SiteFooter /></div>;
}
